model_name: mnoukhov/pythia410m-tldr-sft
dataset_name: mnoukhov/openai_summarize_comparisons_tldrprompt_relabel1b
# gold_model_name: mnoukhov/pythia1b-sft-rm-tldrprompt
max_prompt_length: 512
max_target_length: 131
max_length: 640
lr_scheduler_type: cosine
## hub stuff
push_to_hub: True
push_to_hub_organization: mnoukhov
## training stuff
gold_eval: ppl
eval_steps: 0.2
save_steps: 0.2
beta: 0.05
max_steps: -1
num_train_epochs: 1
load_in_8bit: False
bf16: False
fp16: True
learning_rate: 1e-5
use_peft: True
lora_r: 16
lora_alpha: 32
lora_dropout: 0.
gradient_accumulation_steps: 4
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
