output_dir: summarize_from_feedback_tldr3_generated_20k_relabel_pythia1b_dpo
mode: relabel
model_name: vwxyzjn/EleutherAI_pythia-1b-deduped__dpo__tldr
model_revision: dpo__55513__1707379566 
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: mnoukhov/summarize_from_feedback_tldr3_generated_20k_vllm_pythia1b_dpo
eval_split: train
use_peft: False
beta: 0.5
load_in_8bit: False
bf16: True
fp16: False
per_device_eval_batch_size: 8
warmup_steps: 150
