train_split: train[:1000]
eval_split: validation[:10]
##
model_name: vwxyzjn/EleutherAI_pythia-1b-deduped__sft__tldr
model_revision: sft__55513__1706646024
dataset_name: vwxyzjn/summarize_from_feedback_oai_preprocessing_1706381144
prompt_field: query
gold_eval: ppl
beta: 0.5
num_train_epochs: 3
eval_steps: 750
load_in_8bit: False
bf16: False
fp16: True
learning_rate: 1e-5
use_peft: True
lora_r: 8
lora_alpha: 32
lora_dropout: 0.05
gradient_accumulation_steps: 4
per_device_train_batch_size: 4
warmup_steps: 150
save_steps: 100
eval_first_step: False
