model_name: vwxyzjn/EleutherAI_pythia-2.8b-deduped__ppo_left_padding_new_nowhiten_reward__tldr
model_revisions: ["ppo_left_padding_new_nowhiten_reward__55513__1710356835"]
gen_dtype: bfloat16
wandb_log_id: EleutherAI_pythia-2.8b-deduped__ppo_left_padding_new_nowhiten_reward__tldr_55513
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
gold_model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_new_tokens: 128
max_length: 640
temperature: 0.010001
