model_name: vwxyzjn/EleutherAI_pythia-1b-deduped__dpo__tldr
model_revisions: ["dpo__55513__1707379566"]
gen_dtype: bfloat16
wandb_log_id: EleutherAI_pythia-1b-deduped__dpo__tldr_55513
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
gold_model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_new_tokens: 53
max_length: 565
