model_name: mnoukhov/EleutherAI_pythia-1b-deduped__sft__tldr_dpo2_costa_1b_20k_fp16.yml_0c78169_484b8_merged 
gen_dtype: bfloat16
wandb_log_id: dpo2_costa_1b_20k_fp16_length128
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
gold_model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_new_tokens: 128
max_length: 630
temperature: 0.010001
