model_name: mnoukhov/dpo2_costa_1b_20k_fp16.yml_84732ba32bb369f203401efc31180c78
wandb_log_id: model_name
base_model_name: mnoukhov/EleutherAI_pythia-1b-deduped__sft__tldr_dpo_costa_1b_fp16.yml_3d94f50_b9ff2_merged
gen_dtype: bfloat16
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
gold_model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_new_tokens: 128
max_length: 640
temperature: 0.010001
