predict_relabel: True
output_dir: /home/toolkit/huggingface/openai_summarize_comparisons_tldrprompt_relabel1b
model_name: mnoukhov/pythia1b-sft-rm-tldrprompt
dataset_name: mnoukhov/openai_summarize_comparisons_tldrprompt
train_split: train
eval_split: test[:5000]
load_in_8bit: False
bf16: False
fp16: True
use_lora: False
per_device_eval_batch_size: 8
padding: do_not_pad
