model_name: /home/toolkit/huggingface/tldr_sft_pythia410m_fp32_trainall_3epochs
load_in_8bit: False
bf16: False
fp16: True
use_lora: False
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: False
learning_rate: 5e-6
optimizer_type: adamw_torch
num_train_epochs: 3
seq_length: 560
