tokenizer_name: EleutherAI/pythia-1b-deduped
model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_length: 640
dataset_name: mnoukhov/summarize_from_feedback_tldr3_unlabelled_vllm_dpo_costa_2.8b_bf16.yml_6e799 
dataset_split: train[:10]
