model_name: "EleutherAI/pythia-6.9b-deduped"
log_with: "wandb"
lr_scheduler_type: cosine
num_warmup_steps: 100
weight_decay: 0.05
load_in_8bit: True
use_peft: True
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
bf16: True
streaming: True
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
num_train_epochs: 1
max_steps: -1
gradient_checkpointing: False
streaming: False
