model_name: "EleutherAI/pythia-6.9b-deduped"
log_with: "wandb"
learning_rate: 1e-5
lr_scheduler_type: cosine
num_warmup_steps: 100
weight_decay: 0.05
load_in_8bit: True
use_peft: True
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
bf16: False
streaming: False
gradient_checkpointing: False
gradient_accumulation_steps: 8
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
train_completions: True
num_train_epochs: 2
