model_name: "EleutherAI/pythia-6.9b-deduped"
log_with: "wandb"
learning_rate: 1e-5
lr_scheduler_type: cosine
num_warmup_steps: 100
weight_decay: 0.05
load_in_8bit: False
use_peft: True
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
fp16: True
fp16_model: True
bf16: False
streaming: False
gradient_checkpointing: False
gradient_accumulation_steps: 16
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
train_completions: False
num_train_epochs: 3
optimizer_type: adamw_torch
