model_name: "EleutherAI/pythia-14m"
log_with: "wandb"
learning_rate: 1e-5
lr_scheduler_type: cosine
num_warmup_steps: 100
weight_decay: 0.05
load_in_8bit: False
use_peft: False
fp16: False
bf16: False
streaming: False
gradient_checkpointing: False
gradient_accumulation_steps: 4
per_device_train_batch_size: 32
per_device_eval_batch_size: 8
train_completions: True
num_train_epochs: 1
seq_length: 560
