output_dir: summarize_from_feedback_tldr3_generated_20k_vllm_pythia1b_dpo_temp0.7_length128
dataset_name: mnoukhov/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
model_name: vwxyzjn/EleutherAI_pythia-1b-deduped__dpo__tldr
revision: dpo__55513__1707379566 
tokenizer_name: EleutherAI/pythia-1b-deduped
train_split: train[:20000]
batch_size: 4
seq_length: 512
max_new_tokens: 128
temperature: 0.7
top_p: 1.0
dtype: auto
