output_dir: summarize_from_feedback_tldr3_unlabelled_vllm_dpo2_costa_1b_fp16.yml_bfcef025a6601addfa2207f3e3755835
dataset_name: mnoukhov/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144_unlabelled
model_name: mnoukhov/dpo2_costa_1b_20k_fp16.yml_bfcef025a6601addfa2207f3e3755835
base_model_name: vwxyzjn/EleutherAI_pythia-1b-deduped__sft__tldr
base_model_revision: sft__55513__1706646024
lora_model: True
tokenizer_name: EleutherAI/pythia-1b-deduped
train_split: train
batch_size: 4
max_prompt_length: 512
max_new_tokens: 128
temperature: 0.7
top_p: 1.0
dtype: bfloat16
