# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"flatten_dict": "00-core.ipynb",
         "stack_dicts": "00-core.ipynb",
         "add_suffix": "00-core.ipynb",
         "pad_to_size": "00-core.ipynb",
         "logprobs_from_logits": "00-core.ipynb",
         "whiten": "00-core.ipynb",
         "clip_by_value": "00-core.ipynb",
         "entropy_from_logits": "00-core.ipynb",
         "average_torch_dicts": "00-core.ipynb",
         "stats_to_np": "00-core.ipynb",
         "build_bert_batch_from_txt": "00-core.ipynb",
         "ValueHead": "01-gpt2-with-value-head.ipynb",
         "GPT2HeadWithValueModel": "01-gpt2-with-value-head.ipynb",
         "respond_to_batch": "01-gpt2-with-value-head.ipynb",
         "AdaptiveKLController": "02-ppo.ipynb",
         "FixedKLController": "02-ppo.ipynb",
         "PPOTrainer": "02-ppo.ipynb"}

modules = ["core.py",
           "gpt2.py",
           "ppo.py"]

doc_url = "https://lvwerra.github.io/trl/"

git_url = "https://github.com/lvwerra/trl/tree/master/"

def custom_doc_links(name): return None
