repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/huggingface/doc-builder
    rev: 7e31a94f70994bd73656a81690b13aaed439e798  # main
    hooks:
      - id: doc-builder-style
        args: [--max_len, "119"]
        files: ^(trl|tests|docs/source)/
