repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/huggingface/doc-builder
    rev: 9978a4134f9e245a927f8d85f73c026609b38b47  # main
    hooks:
      - id: doc-builder-style
        args: [--max_len, "119"]
        files: ^(trl|tests|docs/source)/
