apiVersion: v1
kind: Pod
metadata:
  labels:
    qos.coreweave.cloud/latency: low
  name: ppo-trainer-ziyi-run-3
  namespace: tenant-chairesearch-test
spec:
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: model-storage
  imagePullSecrets:
      - name: docker-creds
  containers:
    - name: ppo-trainer-container-ziyi-run-3
      image: gcr.io/chai-959f8/training:ppo-trainer-ziyi
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 124Gi
        requests:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 124Gi
      volumeMounts:
        - name: model-storage
          mountPath: /models
      env:
        - name: RUN_NAME
          value: "run-3"
        - name: PROJECT_NAME
          value: "ppo-tuning"
        - name: TEMPERATURE
          value: "0.8"
        - name: GAMMA
          value: "0.9"
        - name: ADAP_KL_CTRL
          value: "True"
        - name: VF_COEF
          value: "0.2"
        - name: LAM
          value: "0.9"
        - name: STORAGE_URI
          value: pvc://model-storage/
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        failureThreshold: 1
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 5
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - ORD1
        - weight: 20
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_80GB
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_80GB
