name: Test self hosted

on:
  pull_request:

jobs:
  dummy:
    runs-on:
      group: aws-g4dn-2xlarge
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Echo dummy
        run: |
          echo "Dummy test"
