name: Test self hosted

on:
  pull_request:

jobs:
  dummy:
    runs-on:
      group: aws-g4dn-2xlarge
    container:
      image: huggingface/trl-latest-gpu:latest
      options: --gpus all --shm-size "16gb" -e NVIDIA_DISABLE_REQUIRE=true
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Echo dummy
        run: |
          echo "Dummy test"
