name: Test self-hosted on all groups

on:
  pull_request:

jobs:
  dummy:
    # Run of a miachine with 1 GPU
    runs-on:
      group: aws-g4dn-2xlarge
    container:
      image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Echo dummy
        run: echo "Dummy"

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y make
          # We use uv as its 2x faster for installing packages than pip
          pip install uv
          uv pip install ".[dev]" --system

      - name: Test with pytest
        run: |
          make test