on:
  push:

name: Secret Leaks

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@7635b24fd512a2e817dd3e9dd661caaf035a079d  # v3.93.1
      with:
        # exclude buggy postgres detector that is causing false positives and not relevant to our codebase
        extra_args: --results=verified,unknown --exclude-detectors=postgres
