name: Upload PR Documentation

on:
  workflow_run:
    workflows: ["Build PR Documentation"]
    types:
      - completed

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/upload_pr_documentation.yml@0f4784322c564503c4a4d67ccb7fba29e32f111a  # main
    with:
      package_name: trl
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
      comment_bot_app_id: ${{ secrets.COMMENT_BOT_APP_ID }}
      comment_bot_secret_pem: ${{ secrets.COMMENT_BOT_SECRET_PEM }}
