name: Upload PR Documentation

on:
  workflow_run:
    workflows: ["Build PR Documentation"]
    types:
      - completed

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/upload_pr_documentation.yml@2f7376e5d3e4a8857f511d932e9d8f652711e461  # main
    with:
      package_name: trl
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
      comment_bot_app_id: ${{ secrets.COMMENT_BOT_APP_ID }}
      comment_bot_secret_pem: ${{ secrets.COMMENT_BOT_SECRET_PEM }}